apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gvin
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-gvin@sha256:ff270f739de284652d759bdc57f38e21ab9d55ad8b8ddbed9e712a8c3d481396
        name: my-nodejs
        resources: {}
status: {}
